version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debian-dev
    entrypoint: # 永久睡眠
      - sleep
      - infinity
    image: debian-dev:v1.0.0
    init: true
    extra_hosts:
      - "raw.githubusercontent.com:185.199.108.133"
      - "github.com:20.205.243.166"
      - "github.global.ssl.fastly.net:75.126.135.131"
      - "assets-cdn.github.com:185.199.110.153"
    hostname: zero
    working_dir: /workspace
    restart: always
    dns:
      - 114.114.114.114
      - 8.8.8.8
    volumes:
      - /workspace
    # volumes:
    # - type: bind
    #   source: /var/run/docker.sock
    #   target: /var/run/docker.sock

