version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debian-dev
    entrypoint: # 永久睡眠
    - sleep
    - infinity
    image: debian-dev:v1.0.0
    init: true
    # volumes:
    # - type: bind
    #   source: /var/run/docker.sock
    #   target: /var/run/docker.sock

